@startuml ldm
!pragma layout smetana
left to right direction
entity Class
entity Student
entity Teacher
entity Enrollment
entity ClassTeacher
entity Class {
  * classId: number <<PK>> - Mã lớp học
  * className: string - Tên lớp học
  * startDate: datetime - Thời gian bắt đầu
  * endDate: datetime - Thời gian kết thúc
  * countStudent: INT - Tổng số lượng sinh viên được phân công
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime - Ngày cập nhật

}
entity Student {
  * studentId: number <<PK>> - Mã sinh viên
  * studentName: string - Tên sinh viên
  * gender: int - Giới tính
  * dob: datetime - Ngày sinh
  * status: int - Trạng thái (Đang học, Đã tốt nghiệp, Bảo lưu, Nghỉ)
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime - Ngày cập nhật
}
entity Teacher {
  * teacherId: number <<PK>> - Mã giảng viên
  * teacherName: string - Tên giảng viên
  * gender: int - Giới tính
  * dob: datetime - Ngày sinh
  * status: int - Trạng thái (Đang dạy, đã nghỉ)
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime - Ngày cập nhật
}
entity Enrollment {
  * enrollmentId: number <<PK>> - Mã bản ghi
  * classId: number <<FK>> - Mã lớp học
  * studentId: number <<FK> - Mã sinh viên
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime - Ngày cập nhật
}
entity ClassTeacher {
  * classTeacherID: number <<PK>> - Mã bản ghi
  * classId: number <<FK>> - Mã lớp học
  * teacherId: number <<FK> - Mã giảng viên
  * createdAt: datetime - Ngày tạo
  * updatedAt: datetime - Ngày cập nhật
}

@enduml
