@startuml AD_TeacherManager_Detail
!pragma layout smetana
title Activity Diagram: Xem chi tiết giảng viên

start
:Truy cập chức năng "Xem chi tiết giảng viên";
if (Có quyền truy cập?) then (Có)
    :Hiển thị màn hình\n(**SCR_TeacherDetail**);
else (Không)
  :Thông báo không có quyền truy cập;
  :Chuyển hướng đến trang chính;
  stop
endif
  :Chọn thao tác;

  switch (Thao tác?)
    case (Xóa)
      :Chuyển sang popup "Xóa giảng viên"
      (Chi tiết tại AD_TeacherManager_Delete);

    case (Đóng)
      :Xác nhận đóng?;
      if (Đồng ý?) then (Có)
        :Quay về danh sách giảng viên\n(**SCR_TeacherManager**);
      else (Không)
        :Ở lại màn hình\n(**SCR_TeacherDetail**);
      endif
  endswitch
  stop
@enduml
