@startuml AD_StudentManager_Create
!pragma layout smetana
title Activity Diagram: Thêm mới sinh viên

start
:Truy cập chức năng "Thêm mới sinh viên";

if (Có quyền truy cập?) then (Có)
  :Hiển thị màn hình\n(**SCR_StudentCreate**);
else (Không)
  :Thông báo không có quyền truy cập;
  :Chuyển hướng đến trang chính;
  stop
endif
  
  :Nhập thông tin sinh viên\n(tên sinh viên, giới tính, ngày sinh, trạng thái);

  :Chọn thao tác;

  switch (Thao tác?)
    case (Lưu)
      :Kiểm tra tính hợp lệ dữ liệu;
      if (Hợp lệ?) then (Đúng)
        :Ghi nhận dữ liệu sinh viên;
          if (Ghi thành công?) then (Có)
            :Thông báo "Thêm mới sinh viên thành công";
            :Chuyển hướng về danh sách\n(**SCR_StudentManager**);
          else (Không)
            :Thông báo lỗi hệ thống;
            :Ở lại màn hình màn hình\n(**SCR_StudentCreate**);
          endif
      else (Sai)
        :Thông báo lỗi "Nhập đầy đủ trường thông tin bắt buộc"";
        :Ở lại màn hình\n(**SCR_StudentCreate**);
      endif
    case (Đóng)
      :Xác nhận hủy thao tác?;
      if (Đồng ý?) then (Có)
        :Hủy thao tác;
        :Chuyển hướng về danh sách\n(**SCR_StudentManager**);
      else (Không)
        :Ở lại màn hình\n(**SCR_StudentCreate**);
      endif
  endswitch
  stop
@enduml
