@startuml AD_ClassManager_Update
!pragma layout smetana
title Activity Diagram: Chỉnh sửa lớp học

start
:Truy cập chức năng "Chỉnh sửa lớp học";
:Chọn bản ghi cần chỉnh sửa;
if (Được phép sửa) then (Có)
    :Hiển thị màn hình\n(**SCR_ClassUpdate**);

    :Nhập thông tin lớp học\n(tên lớp, thời gian bắt đầu, thời gian kết thúc);

    :Chọn thao tác;

    switch (Thao tác?)
      case (Lưu)
        :Kiểm tra tính hợp lệ dữ liệu;
        if (Hợp lệ?) then (Đúng)
          :Ghi nhận cập nhật lớp học;
          if (Cập nhật thành công?) then (Có)
            :Thông báo "Chỉnh sửa lớp học thành công";
            :Chuyển hướng về danh sách\n(**SCR_ClassManager**);
          else (Không)
            :Thông báo lỗi hệ thống;
            :Ở lại màn hình\n(**SCR_ClassUpdate**);
          endif
        else (Sai)
          :Thông báo lỗi "Nhập đầy đủ trường thông tin bắt buộc";
          :Ở lại màn hình\n(**SCR_ClassUpdate**);
        endif

      case (Đóng)
        :Xác nhận hủy thao tác?;
        if (Đồng ý?) then (Có)
          :Hủy thao tác;
          :Chuyển hướng về danh sách\n(**SCR_ClassManager**);
        else (Không)
          :Ở lại màn hình\n(**SCR_ClassUpdate**);
        endif
    endswitch

  else (Không)
  endif

stop
@enduml
